### ISSUE TITLE
Double authorization + double stock reductions + double emails to customers

### ISSUE THREAD

**Issue by cpiechotta** [reepay/reepay-woocommerce-payment#100]
There is a race condition between the use of the accept url and the webhook. This sporadically, if the timing is right, results in double authorizations, double notes on orders and double stock reduction calls - **which is a nightmare for logistics**.

Even though there are checks for a DB value which tries to mitigate this it doesn't prevent the issue (since it's a race condition). 

It seems there has been implemented multiple checks, which actually try to verify if a webhook is configured and then only use that. This still doesn't work as intended though. We've verified that our webhook is configured and that the value for this in the database reflects this. When the check is performed it seems that the accept url is still being used however so there must be an issue with reading out the value somewhere. 

Adding more logging with regards to what method was used for authorization/refund could help troubleshoot this further.

**Comment by cpiechotta** [comment]
@markusbrunke any news on this being fixed?

**Comment by cpiechotta** [comment]
Thank you for the suggestion @maxwhite. It is my understanding from talks with @markusbrunke is that MobilePay is relying on the accept URL I just want to make sure that commenting out this line will not adversely affect that payment method?

**Comment by maxwhite** [comment]
H @cpiechotta , no MobilePay is also rely on webhook so commenting this line should be safe

**Comment by maxwhite** [comment]
releted to https://github.com/reepay/reepay-woocommerce-payment/issues/117 
can be closed

**Comment by cpiechotta** [comment]
I'm not seeing this as being related to #117 this has been an issue for more than a year.

Also it seems to be more frequent if the gateway method used is "Overlay" and not "Window"

This issue should be reopened.

**Comment by maxwhite** [comment]
@cpiechotta , the issue have already been solved and we have no other merchants complaining about this issue. We can't reproduce this issue and are not experiencing this in any of our test shops either.

**Comment by cpiechotta** [comment]
Thank you for clarifying I'll be monitoring this after our recent update to 1.4.4
