### ISSUE TITLE
Plugin not translateable

### ISSUE THREAD

**Issue by emilwibe** [reepay/reepay-woocommerce-payment#102]
Hi at Repay

The plugin isn't "properly prepared" for translation in the WordPress repository. By preparing your plugin for localization people in the WordPress community around the world are able to translate your plugin for you.

https://translate.wordpress.org/projects/wp-plugins/reepay-checkout-gateway/
https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/

Kind regards

**Comment by dimaspolohov** [comment]
@markusbrunke We are thinkig thats done, we are add some strings to translate and change textdomain (textdomain nedd to be equal WP market plugin slug)
