### ISSUE TITLE
Double orders since updating to WC plugin 1.4.4

### ISSUE THREAD

**Issue by cpiechotta** [reepay/reepay-woocommerce-payment#117]
Since updating to Reepay v.1.4.4 we are getting double orders for every order placed by the customer.

There seems to be an issue where and order is created and the first time an invoice is requested from the Reepay API the response returned is a 404 Not Found for that order. Just after this a new order is created and another request to the Reepay API is sent for this invoice - this returns a 200 OK.

**Se log trace:** 
```
08-31-2021 @ 14:06:39 - Request: GET https://api.reepay.com/v1/invoice/order-MC-41245 []
08-31-2021 @ 14:06:39 - [0.1457] HTTP Code: 404. Response: {"code":31,"error":"Invoice not found","path":"/v1/invoice/order-MC-41245","timestamp":"2021-08-31T12:06:39.359+00:00","http_status":404,"http_reason":"Not Found","request_id":"a90731f1fa3aab7d5d906570c335b34e"}
08-31-2021 @ 14:06:50 - Request: GET https://api.reepay.com/v1/invoice/order-MC-41246 []
08-31-2021 @ 14:06:51 - [0.1287] HTTP Code: 200. Response: {"id":"420272671419c1410794cacc924d788d","handle":"order-MC-41246","customer":"cust-2022","state":"authorized","type":"ch","amount":48800,"number":29263,"currency":"DKK","due":"2021-08-31T11:26:47.852+00:00","authorized":"2021-08-

```

**Comment by maxwhite** [comment]
Hi @cpiechotta , I'm looking into this issue. 
Could you contact me by email: maxim@reepay.com

**Comment by cpiechotta** [comment]
After our talks this issue seems to be not directly related to the Reepay plugin - thank you for your input @maxwhite.
