### ISSUE TITLE
Separate MobilePay Online And ViaBill Payment Method

### ISSUE THREAD

**Issue by markusbrunke** [reepay/reepay-woocommerce-payment#12]
The plugin doesn't support separate MobilePay Online and ViaBill payment methods. That means at the moment, that you can't choose your preferred payment method directly on the WooCommerce checkout page. See the picture.

![image](https://user-images.githubusercontent.com/49717740/56288117-538a5a80-611e-11e9-9136-4c08a69fa58a.png)

It would give a better experience if you were able to present for example Mobile Pay Online directly on the WooCommerce checkout page.

![image](https://user-images.githubusercontent.com/49717740/56288323-d3b0c000-611e-11e9-9093-5506f6b9d768.png)

**Comment by RuneNisbeth** [comment]
The payment methods that we wish to be separate options are:

Kort (Dankort, Visa, mastercard, electron, maestro, dinersclub, discover, amex, Forbrugsforeningen, jcb union pay)
Viabill,
Applepay,
Mobilepay,
Klarna slice it,
Klarna Pay Later, 
Klarna Pay Now 
Paypal,
Swish, 
Resurs Bank,
