### ISSUE TITLE
Keeps asking if I want to settle when I'm updating order although settle has been done

### ISSUE THREAD

**Issue by markusbrunke** [reepay/reepay-woocommerce-payment#125]
![image](https://user-images.githubusercontent.com/49717740/152650436-852f929d-5ca2-476f-ba15-e19bd001c350.png)

**Comment by dimaspolohov** [comment]
@markusbrunke Thats done, but I see some more bugs with this feature:
1. If this alert is apear with right condition, and we click OK, ammount not captured
2. If we captire specified ammount before, this alert offers to us capture full amount and ignore alleady captured summ https://prnt.sc/-biH7-372gSh

**Comment by markusbrunke** [comment]
@dimaspolohov That is correct behavior. The reason why we have that notice is to avoid making a full capture when you change the order status to completed.

Let's say you have an order of 100 USD. You would like to only settle/capture 80 USD. Then you use the Reepay Widget to settle the correct amount, meaning that there is 20 USD left as a reservation. If you change the order status to completed, reepay will by default try to capture the full amount. This notice stops the API call that captures the full amount, giving the merchant the option to select whether they want to settle/capture the remaining 20 USD. 

The issue is, that you see this notice although all 100 USD have been settled if that was the case.

**Comment by dimaspolohov** [comment]
@markusbrunke Ok, that commited
