### ISSUE TITLE
Customer already exist, Country is not ISO

### ISSUE THREAD

**Issue by markusbrunke** [reepay/reepay-woocommerce-payment#130]
We have already implemented a fallback if the plugin experience the error **invoice already settled**. This fallback function can be activated by enabling Order handle failover in the settings.

Besides this error we also currently experiencing **customer already exist** and **country is not ISO** standard. We need similar fallback methods for these errors. E.g. if Reepay response with a customer already exists, create fallback customer cust_1235-1.

**Comment by markusbrunke** [comment]
Instead of having a fallback method for **country is not ISO**, we should simply make sure no value is posted to Reepay

**Comment by dimaspolohov** [comment]
@markusbrunke Hi, for create the fallback we need to receive error code, I don't see 'customer already exist' error in the errors list https://api.reepay.com/v1/error_codes
About Country codes - Woocommerce return code in ISO 3166-1 alpha-2 and I what you API use same format, we can add condition for country arg https://wp-kama.ru/plugin/woocommerce/function/WC_Countries::country_exists and clear

**Comment by markusbrunke** [comment]
@dimaspolohov  Forget customer already exist for now.

The issue with country is not ISO, is that some merchants are using plugins that remove the country field from WooCommerce checkout meaning, and in these cases, they receive this error. In the past, we have just asked the merchant to enable the country field again and hide it with CSS, but my guess is we might be sending some default text in the country field, which triggers the country is not ISO error.

**Comment by dimaspolohov** [comment]
@markusbrunke We can send null or empty value for this.

**Comment by markusbrunke** [comment]
@dimaspolohov Please send empty value for this :-)

**Comment by dimaspolohov** [comment]
@markusbrunke Hi, That commited
