### ISSUE TITLE
Change save card logos to use normal Reepay payment method logos

### ISSUE THREAD

**Issue by markusbrunke** [reepay/reepay-woocommerce-payment#134]
![image](https://user-images.githubusercontent.com/49717740/166974848-d6330721-a9a4-4cfd-be6d-4f501f022847.png)

**Comment by markusbrunke** [comment]
Beautify section as well. 
![image](https://user-images.githubusercontent.com/49717740/166974923-38139306-572c-4004-8026-63c6a8496634.png)

**Comment by markusbrunke** [comment]
@dimaspolohov Not sure if this is already done?

**Comment by dimaspolohov** [comment]
@markusbrunke Can you explain please?

**Comment by markusbrunke** [comment]
@dimaspolohov Never mind. This is done.
