### ISSUE TITLE
Woocommerce 7.1.0 double ordres

### ISSUE THREAD

**Issue by Zekcode** [reepay/reepay-woocommerce-payment#170]
After Woocommerce update to 7.1.0 we have issues with that ordres at made twice, one correct and one cancled with another post id/ordre id.

we deactivated almost everything to point the issue at the Reepay Plugin.
Then we activated everything agian and deactivated Reepay and createde alternative payment options.

Everything works without Reepay enabled.

**Comment by m-overlund** [comment]
Same here 
- suddenly started getting lots of double orders (which were almost zero beforehand).

**Comment by Zekcode** [comment]
> 

For now, just downgrade woocommerce from 7.1.0 to 7.0.1
in the bottom here you can download it [here](https://wordpress.org/plugins/woocommerce/advanced/)
