### ISSUE TITLE
Error settling shipping cost

### ISSUE THREAD

**Issue by TeiturB** [reepay/reepay-woocommerce-payment#172]
Since the release of woocommerce 7.1, i've had a fair share of errors regarding duplicate orders and separately charged items.
Most issues were patched, however, I still have an error on settling the shipping cost, where I get:
Failed
code: 922
Acquirer message : NETS: Message number out of sequence
Error : ACQUIRER ERROR

Any timeline for this issue?

**Comment by TeiturB** [comment]
Seems to also have affected some singular items as well...

**Comment by markusbrunke** [comment]
@TeiturB Please submit a ticket to support@reepay.com and provide us with your WordPress credentials, so we can take a look at it! This message is coming from Nets and is not necessarily due to the plugin: NETS: Message number out of sequence. But we will be happy to look at the issue.
