### ISSUE TITLE
Show account info when API key has been saved

### ISSUE THREAD

**Issue by markusbrunke** [reepay/reepay-woocommerce-payment#183]
For both the Subscription plugin and Payment plugin. Once the private key has been activated get account details such as the name and display that. Also, tell whether the webhook has been configured properly and is active or not, and the state of the account

See screenshots:

- When a private key is pasted in as enabled.
- When a private key is not enabled. I would like to have a button that gives you the option to "Save and verify". Once this is done you will see the account, state, and webhook

![Image](https://user-images.githubusercontent.com/49717740/206284978-f7054635-f29c-4580-9370-33e864d34ec4.png)

![Image](https://user-images.githubusercontent.com/49717740/206284731-cea00e4b-ebc8-4dcd-b394-a82fdd8b3e8e.png)

**Comment by dimaspolohov** [comment]
@markusbrunke How we must check webhook status?

**Comment by dimaspolohov** [comment]
@markusbrunke And we need the access to live key on our live account

**Comment by markusbrunke** [comment]
@dimaspolohov You are already using the webhook status today. It is already implemented. We just need it for both the live and test private key/account.

_And we need the access to live key on our live account_ What do you mean by this?

**Comment by dimaspolohov** [comment]
@markusbrunke We are dont have live keys for test, on our live dashboard not exist this menu section 
![image](https://user-images.githubusercontent.com/81742762/209533238-7771e71e-cba6-47c1-a6ae-c5f85def9f03.png)
