### ISSUE TITLE
Add Anyday as payment method

### ISSUE THREAD

**Issue by markusbrunke** [reepay/reepay-woocommerce-payment#191]
_AnyDay allows customer to split up their payments into several rates. If you have setup AnyDay on the Payment Methods page in the Reepay administration, the payment option will automatically be presented in Reepay Checkout.

Note the AnyDay payment option is only presented if the currency is DKK and only for amounts over 300 DKK._

![Image](https://user-images.githubusercontent.com/49717740/210529171-7e889752-8766-481f-9175-5fc5772d1541.png)

**Comment by dimaspolohov** [comment]
@markusbrunke Here?


![Image](https://user-images.githubusercontent.com/81742762/214029902-194734de-7221-4c68-a13e-bb30ffb3539b.png)

**Comment by markusbrunke** [comment]
@dimaspolohov No here: 
![image](https://user-images.githubusercontent.com/49717740/214033732-12c9c5ad-2bf5-4050-9481-7076bcf14493.png)

Note that this payment method only works for regular payments. Not recurring payments.

Also while you are at it, Apple Pay now also works for recurring payments (subscriptions), but only if the recurring flag is true:

![image](https://user-images.githubusercontent.com/49717740/214034043-c7fd774d-0bbe-4665-81c5-9b32d1cbe4fc.png)

This end point, which I belive we already use to check if the merchant have configured the payment method in Reepay: https://reference.reepay.com/api/ui/#/agreement/getGatewayAgreements

**Comment by dimaspolohov** [comment]
@markusbrunke Can you add Anyday on our test account on Reepay side?
