### ISSUE TITLE
Maestro has wrong dimensions, messes up the grid

### ISSUE THREAD

**Issue by cpiechotta** [reepay/reepay-woocommerce-payment#208]
The Maestro card has wrong dimensions compared to the other cards, which makes the layout of the cards in checkout skewed. General styling and structure of the cards being shown in the checkout should be looked over.

**Visa and Dankort looks correct and the other cards follow these dimensions:**
<img width="919" alt="Screenshot 2023-03-02 at 09 36 13" src="https://user-images.githubusercontent.com/8568006/222375671-314eb829-b88a-414a-9e5d-dd1b47594934.png">

<img width="996" alt="Screenshot 2023-03-02 at 09 43 19" src="https://user-images.githubusercontent.com/8568006/222376951-8871dc71-08ab-46af-87fe-ce77790c9455.png">

**Maestro should follow the same dimensions etc. and please note the excessive file size of this asset (70+ kb compared to 3+ kb of the other assets) - this asset needs to be updated and have the same properties as the others.**
<img width="832" alt="Screenshot 2023-03-02 at 09 36 43" src="https://user-images.githubusercontent.com/8568006/222375677-5b7c09f0-1ca5-47f7-8553-ffa793b89cbd.png">

**Comment by Daniel217D** [comment]
https://github.com/reepay/reepay-woocommerce-payment/pull/241
