### ISSUE TITLE
Code refactroing

### ISSUE THREAD

**Issue by Daniel217D** [reepay/reepay-woocommerce-payment#210]
- [x] Set up composer
- [x] Improve assets generation via gulp
- [x] Add a script to archive the plugin for further installation
- [x] Add wpcs (WordPress Code Standarts) to check code quality
- [x] Remove commented out or simply unused code
- [x] Add function to replace wc_get_template in plugin
- [x] Remove code duplication in gateways
- [x] Set up namespaces and code autoloading
- [x] Improve code splitting into logical parts

**Comment by Daniel217D** [comment]
- [ ] Add wpcs (WordPress Code Standarts) to check code quality
- [ ] Remove commented out or simply unused code
- [ ] Set up composer, namespaces and code autoloading
- [ ] Improve code splitting into logical parts
- [ ] Remove code duplication in gateways
- [ ] Move settings from the Reepay Checkout gateway to a separate settings page

**Comment by cpiechotta** [comment]
With regards to this:
"Move settings from the Reepay Checkout gateway to a separate settings page"

Please leave all Reepay settings under Payments -> Reepay. 
Please be a good WooCommerce ecosystem citizen and do not deviate from the conventions.
