### ISSUE TITLE
Payment confirm action

### ISSUE THREAD

**Issue by markusbrunke** [reepay/reepay-woocommerce-payment#28]
This functions runs 3 times. 

![image](https://user-images.githubusercontent.com/49717740/57081201-90487b00-6cf4-11e9-9166-ce7b8adddcd8.png)

LOGS:
05-01-2019 @ 11:18:11 - WC_Gateway_Reepay_Checkout::WC_Gateway_Reepay_Checkout::payment_confirm Incoming data array (
  'key' => 'wc_order_RSjlcQMOv53nq',
  'id' => 'xxxxxxxxxxxxxxxxxxxxxxxx',
  'customer' => 'cust-0009',
  'payment_method' => 'xxxxxxxxxxxxxxxxxxxxxxxx',
)
05-01-2019 @ 11:18:12 - WC_Gateway_Reepay_Checkout::WC_Gateway_Reepay_Checkout::payment_confirm Incoming data array (
  'key' => 'wc_order_RSjlcQMOv53nq',
  'id' => 'xxxxxxxxxxxxxxxxxxxxxxxx',
  'customer' => 'cust-0009',
  'payment_method' => 'xxxxxxxxxxxxxxxxxxxxxxxx',
)
05-01-2019 @ 11:18:12 - WC_Gateway_Reepay_Checkout::WC_Gateway_Reepay_Checkout::payment_confirm Incoming data array (
  'key' => 'wc_order_RSjlcQMOv53nq',
  'id' => 'xxxxxxxxxxxxxxxxxxxxxxxx',
  'customer' => 'cust-0009',
  'payment_method' => 'xxxxxxxxxxxxxxxxxxxxxxxx',
)

**Comment by robert-mygind** [comment]
+1
