### ISSUE TITLE
WooCommerce Subscription Coupon Issue

### ISSUE THREAD

**Issue by markusbrunke** [reepay/reepay-woocommerce-payment#33]
When you create coupons in WooCommerce and use them, the correct amount will not be transferred to the payment window.

![image](https://user-images.githubusercontent.com/49717740/58007265-34e6fd00-7aea-11e9-84c3-52143459d17a.png)

![image](https://user-images.githubusercontent.com/49717740/58007412-842d2d80-7aea-11e9-9702-8dd2c26edb1f.png)

**Comment by aait** [comment]
We need to see the exact discount rule. Can you provide screenshot or access to the shop?

**Comment by markusbrunke** [comment]
@aait I have sent access to you on mail

**Comment by aait** [comment]
Suggest this is a conflict with WOOCS - WooCommerce Currency Switcher

![image](https://user-images.githubusercontent.com/6286270/58316607-3713c900-7e14-11e9-9baf-fc4eab235d4f.png)
Coupons works fine in a vanilla Woo
Please uninstall WOOCS - WooCommerce Currency Switcher  and see if it works after that. If it works without WOOCS installed maybe try another one like WPML currency support.
