### ISSUE TITLE
Manuel Woo Subscription Sign Up From Backend

### ISSUE THREAD

**Issue by markusbrunke** [reepay/reepay-woocommerce-payment#40]
You can't create a new subscriber in WooCommerce Subscription from the Woo Backend:

![image](https://user-images.githubusercontent.com/49717740/63416152-3680d380-c3ff-11e9-90f6-4dd59d6c2a10.png)

**Comment by RuneNisbeth** [comment]
This error is also uncaught when trying to change the Reepay token on the subscription.
