### ISSUE TITLE
Partial Capture from WooCommerce

### ISSUE THREAD

**Issue by markusbrunke** [reepay/reepay-woocommerce-payment#8]
The plugin doesn't support the edit feature, which allows you to change the amount of an order. We can't, of course, allow increasing the amount from for example 4 kr. to 5 kr. but merchant should be able to decrease from for example 4 kr. to 3 kr. like in the example below.  You can edit the price in WooCommerce, but Reepay makes a full capture of the first amount. 

![image](https://user-images.githubusercontent.com/49717740/56284330-7a439380-6114-11e9-8bc5-ab67c60efa6e.png)

![image](https://user-images.githubusercontent.com/49717740/56284351-87f91900-6114-11e9-943d-cd7ca6a66b14.png)

![image](https://user-images.githubusercontent.com/49717740/56284366-90515400-6114-11e9-84cf-2a9ce0c123a5.png)

![image](https://user-images.githubusercontent.com/49717740/56284407-a828d800-6114-11e9-9fa3-b8fce097caf9.png)

![image](https://user-images.githubusercontent.com/49717740/56284427-b676f400-6114-11e9-9a90-598b6ca1cc15.png)

![image](https://user-images.githubusercontent.com/49717740/56284445-becf2f00-6114-11e9-8a94-c84b066d2f99.png)

**Comment by chnutzen** [comment]
I have pushed an update for this issue. It can be downloaded on this fork: https://github.com/chnutzen/reepay-woocommerce-payment. Still needs to be merges to master.

@markusbrunke  - please try my update and let me know if it also works for you.
