### ISSUE TITLE
giftup.app - doesn't calculate gift card value with reepay module. 

### ISSUE THREAD

**Issue by SamuelMaile** [reepay/reepay-woocommerce-payment#89]
What seems to be the problem, once a gift card cupon has been added to the basket the amount is diminished to the correct amount (fx 500kr cupon), when redirected to the reepay payment form the original price is still shown, even though the cupon has been successfully applied. 

Site: https://stagpurebasic.wpengine.com/
Video of issue: https://drive.google.com/file/d/1pwUF0gLZveOxQV9_Jl4jKxWjxAbo93WE/view?usp=sharing

**Comment by KoanLeeroy** [comment]
Hi @SamuelMaile 

I'm the lead for the Gift Up! WP plugin development. Happy to collaborate on a remedy, whether it be in our plugin, or yours.
